// Brainrot SVG Icons
const BRAINROT_SVGS = {
  "Tralalero Tralala": ``,
  "Bombardiro Crocodilo": ``,
  "Chimpanzini Bananini": ``,
  "Capuccino Assassino": ``,
  "Ballerina Cappuccina": ``,
  "Lirilì Larilà": ``,
  "Tung Tung Tung Sahur": ``,
  "Boneca Ambalabu": ``,
  "Brr Brr Patapim": ``,
  "La Vacca Saturno": ``,
  "Bombombini Gusini": ``,
  "Pan Piano Pino": ``,
  "Glorbo Supremo": ``,
  "Bombardiro Crocodilo Omega": ``,
  "Skibidi Toilet": ``,
  "Strawberry Elephant": ``,
  "Frigo Camelo": ``,
  "Pastino Serpentino": ``,
  "Giraffa Crostata": ``,
  "Cactoro Magnifico": ``,
  "Draghino Lasagnoso": ``,
  "Vampiro Risottino": ``,
  "Re Pomodorino": ``,
  "Nebuloso Galassino": ``,
  "Griffin": ``,
  "Love Love Bear": ``,
  "Headless Horseman": ``,
  "Meowl": ``,
  "Noobini Pizzanini": ``,
  "Leone Pastaio": ``
};